apiVersion: v1
kind: Service
metadata:
  name: ctf-postgres-svc
  namespace: ctf
spec:
  type: ClusterIP
  selector:
    app: ctf-postgres
  ports:
    - port: 5432        # the port this Service listens on (within the cluster)
      targetPort: 5432  # the port inside the container to forward to
